plugins {
    id 'com.android.application'
}

android {
    namespace 'com.optimizatudevice.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.optimizatudevice.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }

        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }
}

tasks.register("copyOptimizaApk", Copy) {
    dependsOn("assembleDebug")
    from(layout.buildDirectory.file("outputs/apk/debug/app-debug.apk"))
    into(layout.buildDirectory.dir("outputs/final"))
    rename { "OptimizaTuDevice.apk" }
}
