plugins {
    id 'com.android.application'
}

android {
    namespace 'com.optimizatudevice.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.optimizatudevice.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file("${rootProject.projectDir}/release.keystore")
            storePassword "optimiza123"
            keyAlias "optimiza"
            keyPassword "optimiza123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
