name: Build OptimizaTuDevice APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compilar APK Release
        run: gradle assembleRelease --no-daemon

      - name: Localizar APK
        run: |
          find app/build/outputs -type f -name "*.apk" -print

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: OptimizaTuDevice
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
